api_quiz_quiz_list:
    path: /quizs
    defaults: {_controller: AppBundle:Quiz:list}
    methods: GET

api_quiz_quiz_create:
    path: /users/{id}/quizs
    defaults: {_controller: AppBundle:Quiz:create}
    methods: POST
    requirements:
        id: \d+

api_quiz_quiz_read:
    path: /users/{userId}/quizs/{id}
    defaults: {_controller: AppBundle:Quiz:read}
    methods: GET
    requirements:
        userId: \d+
        id: \d+

api_quiz_users_quiz_list:
    path: /users/{userId}/quizs
    defaults: {_controller: AppBundle:Quiz:userQuiz}
    methods: GET
    requirements:
        userId: \d+
