api_quiz_quiz_list:
    path: /quizs
    defaults: {_controller: AppBundle:Quiz:list}
    methods: GET

api_quiz_quiz_create:
    path: /users/{id}/quizs
    defaults: {_controller: AppBundle:Quiz:create}
    methods: POST
    requirements:
        id: \d+

api_quiz_quiz_read:
    path: /users/{userId}/quizs/{id}
    defaults: {_controller: AppBundle:Quiz:read}
    methods: GET
    requirements:
        userId: \d+
        id: \d+

api_quiz_quiz_delivery:
    path: /quizs/{quizId}/deliver
    defaults: {_controller: AppBundle:Quiz:deliver}
    methods: GET
    requirements:
        quizId: \d+

api_quiz_quiz_pause:
    path: /quizs/{quizId}/pause
    defaults: {_controller: AppBundle:Quiz:pause}
    methods: PUT
    requirements:
        quizId: \d+

api_quiz_quiz_resume:
    path: /quizs/{quizId}/resume
    defaults: {_controller: AppBundle:Quiz:resume}
    methods: PUT
    requirements:
        quizId: \d+

api_quiz_quiz_stop:
    path: /quizs/{quizId}/stop
    defaults: {_controller: AppBundle:Quiz:stop}
    methods: PUT
    requirements:
        quizId: \d+